# Generated by Django 4.1.2 on 2022-12-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='object',
        ),
    ]
