# Generated by Django 4.1.2 on 2023-01-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_title_message_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers',
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.TextField(default='just a test'),
            preserve_default=False,
        ),
    ]
