# Generated by Django 4.1.2 on 2023-02-10 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_remove_message_receivers_message_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='message',
            name='important',
        ),
        migrations.RemoveField(
            model_name='message',
            name='spam',
        ),
        migrations.RemoveField(
            model_name='message',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='message',
            name='trash',
        ),
        migrations.AddField(
            model_name='message',
            name='archive',
            field=models.ManyToManyField(related_name='archived_massages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='important',
            field=models.ManyToManyField(related_name='important_massages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='spam',
            field=models.ManyToManyField(related_name='spam_massages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='starred',
            field=models.ManyToManyField(related_name='starred_massages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='trash',
            field=models.ManyToManyField(related_name='trash_massages', to=settings.AUTH_USER_MODEL),
        ),
    ]
