# Generated by Django 4.1.2 on 2023-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_archive_remove_message_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receivers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
