# Generated by Django 4.1.2 on 2023-04-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
